### PR TITLE
Update pip sources

### PR DESCRIPTION
**Pull request by protheory8**
Didn't test, sorry.

### CODE REVIEW

**Comment by tim77** [comment]
I'll try to build this and test soon. Thank you for PR. I guess this is with new python generator update?

**Comment by protheory8** [comment]
I used [this](https://github.com/flatpak/flatpak-builder-tools/tree/master/pip) thing by executing `./flatpak-pip-generator --requirements-file=requirements.txt --output pypi-dependencies` in Minigalaxy's repo, tag 0.9.4.

**Comment by protheory8** [comment]
I removed commit hash from `minigalaxy` module because that's not really necessary since `flatpak-builder` basically does `git checkout 0.9.4` under the hood. Is that OK?

**Comment by tim77** [comment]
> I removed commit hash from `minigalaxy` module because that's not really necessary since `flatpak-builder` basically does `git checkout 0.9.4` under the hood. Is that OK?

It's better to keep commit hash since this guaranteed that sources will always identical and for reproducible builds. See [example](https://github.com/flathub/com.valvesoftware.Steam.Utility.MangoHud/pull/3#issuecomment-632718912) with `mangohud` package.

Otherwise LGTM. Thanks.

**Pull request merged**
